### PR TITLE
Remove compare page

### PR DESCRIPTION
**Pull request by thejameskyle**

### CODE REVIEW

**Comment by sebmck** [comment]
You can commit straight to master.

On Thursday, 19 March 2015, James Kyle <notifications@github.com> wrote:

> Merged #184 <https://github.com/babel/babel.github.io/pull/184>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel.github.io/pull/184#event-258860695>.
>


-- 
Sebastian McKenzie

**Comment by thejameskyle** [comment]
I just did it instinctually

**Comment by hipertracker** [comment]
Why that page has been removed?

**Comment by sebmck** [comment]
It wasn't kept up to date, was disingenuous and was being used by people to promote Babel based on a superficial and biased chart.

**Pull request merged**
