### PR TITLE
Move loading of all JavaScript close to the end of body tag

### LINKED ISSUE #19: Move script files to end of <body>

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
- Closes #19

- This PR is based on work done in https://github.com/babel/babel.github.io/pull/194 by @peterblazejewicz

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
@peterblazejewicz @thejameskyle Please review!

**Comment by prathamesh-sonpatki** [comment]
Based on https://github.com/peterblazejewicz/babel.github.io/commit/978b949b19c2994dfd58f72b75ed530d5ce19dc0 I will clean it up more. Just wanted to get your thoughts on this approach.

**Comment by peterblazejewicz** [comment]
@prathamesh-sonpatki 
For me it looks OK. I've fetched the PR locally and it works with local Jekyll development server. Do you know specific spots on current babel.io web page that should be carefully checked? (e.g. the Bootstrap js features work, slider works and online editor works, affix and scrollspy both work).
Thanks!

**Comment by prathamesh-sonpatki** [comment]
@peterblazejewicz Yes. I tested slider, repl and bootstrap features also.

**Comment by prathamesh-sonpatki** [comment]
@peterblazejewicz @thejameskyle I completed the cleanups. Please have a look

**Pull request merged**
