### PR TITLE
Added description

### PR DESCRIPTION
**Pull request by nitin42**
Added description for React plugins.

### CODE REVIEW

**Comment by hzoo** [comment]
Thanks!

**Comment by nitin42** [comment]
😄

**Comment by aaronang** [comment]
Fixes #1112. @nitin42 Could you maybe next time refer to the issue you are fixing? This will make it easier for us to maintain 😄  For more information: https://github.com/blog/1506-closing-issues-via-pull-requests. Thanks for your contribution!

**Comment by xtuc** [comment]
Awesome, thanks!

**Pull request merged**
