### PR TITLE
New User: Keymetrics

### LINKED ISSUE #272: New User: Keymetrics
- Name: Keymetrics
- Homepage url: https://keymetrics.io
- Brand Guidelines/Licensing: N/A
- Logo: http://s10.postimg.org/o2n8kg0s9/keymetrics.png

### PR DESCRIPTION
**Pull request by gsvolt**
fixes #272 
added user keymetrics

### CODE REVIEW

**Comment by thejameskyle** [comment]
Please squash into a single commit

**Comment by gsvolt** [comment]
hmm.. having difficulty squashing; let me add a different PR that starts out with all the changes from upstream and then adds the logo - I think I should have done that prior to adding it in my branch. Sorry!

**Comment by thejameskyle** [comment]
You don't need a new PR to do that, you can just force push to the same branch on GitHub.

**Comment by piecioshka** [comment]
@gsvolt try run:
```
git rebase -i 51899f1e027a2e155501d4763702355821b4ff7e
git push -f origin babel.github.io
```

**Comment by thejameskyle** [comment]
ping

**Pull request closed without merging**
