### PR TITLE
Inline install instructions setup

### PR DESCRIPTION
**Pull request by hzoo**
Just adding the cli commands in setup if that makes it clear

### CODE REVIEW

**Comment by jmm** [comment]
Typo `babel-preset-2015 => babel-preset-es2015`. Also, I don't think we should be encouraging people to `npm install babel-preset-es2015` -- they should at least be using the options to save it as a dep (though I never do that -- I just edit `package.json`).

**Comment by hzoo** [comment]
Cool thanks for the catch haha

**Comment by jmm** [comment]
np. Hopefully people can figure out for themselves if they need `--save|--save-dev`.

**Comment by hzoo** [comment]
Yeah hard to say but I assume most of the time people would do `--save-dev`. If they are making a library/dependency on it then they should know `--save`. Otherwise I would just do `npm i babel-preset-es2015 -D` haha

**Pull request merged**
