### PR TITLE
New User: MojoTech

### LINKED ISSUE #447: New User: MojoTech
- Name: MojoTech
- Homepage url: https://mojotech.com
- Brand Guidelines/Licensing: https://www.mojotech.com/toolkit
- Logo: https://mojotech-static.s3.amazonaws.com/m4/zip/mojo_logo_package.zip

### PR DESCRIPTION
**Pull request by sethkrasnianski**
Closes #447.
Ran the svg file through svgo a few times.

### CODE REVIEW

**Comment by samccone** [comment]
:volcano:

**Comment by sethkrasnianski** [comment]
:milky_way:

**Comment by thejameskyle** [comment]
Can you resize it to be 500x200 (2.5x1) and run it through `svgo`?

**Comment by sethkrasnianski** [comment]
@thejameskyle done and done.

**Comment by thejameskyle** [comment]
Thanks!

**Pull request merged**
