### PR TITLE
Add Olapic logo

### PR DESCRIPTION
**Pull request by loverajoel**
Add Olapic as a user

### CODE REVIEW

**Comment by loverajoel** [comment]
@thejameskyle sorry, I closed the previous pr and send another more clean

**Comment by thejameskyle** [comment]
You probably want to center the logo in the svg

**Comment by loverajoel** [comment]
@thejameskyle it's in the center 
image

**Comment by thejameskyle** [comment]
screen shot 2015-11-09 at 1 32 27 pm

**Comment by thejameskyle** [comment]
Needs rebase

**Comment by loverajoel** [comment]
@thejameskyle done and ready to merge

**Pull request merged**
