### PR TITLE
Cleanup plugins code snippets

### PR DESCRIPTION
**Pull request by seedofjoy**
For #1002 

Cleanup & fix `plugins/`

### CODE REVIEW

**Comment by hzoo** [comment]
This might conflict with https://github.com/babel/babel.github.io/pull/1022/files given we are moving most of the content to the other readmes

**Comment by hzoo** [comment]
Sorry yeah 😢

**Comment by seedofjoy** [comment]
Life's hard 😄 

Remove conflicting files

**Comment by existentialism** [comment]
Yeah, they're going to all be moved, so we'll probably just reduce this down to the change in the FAQ?

Also, you're more than welcome to help on the README move: https://github.com/babel/babel.github.io/issues/997#issuecomment-264300866

**Comment by hzoo** [comment]
@seedofjoy forgot if you didn't know about that - basically we were copying and pasting the docs in both places and it seemed better to keep it in the babel/babel repo for github/npm readme

**Pull request merged**
