### PR TITLE
add link for all headings

### PR DESCRIPTION
**Pull request by hzoo**
screen shot 2016-11-09 at 11 18 19 am

Or do it like react with a separate hashtag link thing
screen shot 2016-11-09 at 11 29 44 am

### CODE REVIEW

**Comment by STRML** [comment]
Yeah, I like them fully clickable too (as opposed to the tiny link), but I think it would look a little nicer if we kept the black headers (`h1,h2... a { color: black; }`)

**Comment by hzoo** [comment]
links

Ok only for h2,h3

**Comment by STRML** [comment]
:shipit:

**Comment by danez** [comment]
Wow, you have a serious mouse speed 💨 
😁
Nice addition.

**Pull request merged**
