### PR TITLE
move setup/try buttons

### PR DESCRIPTION
**Pull request by hzoo**
Idea: moving the buttons to the first part of the page? (had to change the color too)

screen shot 2016-11-01 at 12 24 23 am

the Setup color is on hover/active

### CODE REVIEW

**Comment by danez** [comment]
I like that

**Comment by thejameskyle** [comment]
These buttons are not accessible. You need to make it more clear that they are buttons

**Comment by hzoo** [comment]
@thejameskyle should the colors be inverted or should it just have an outline?

**Comment by thejameskyle** [comment]
An outline would be enough

**Comment by hzoo** [comment]
screen shot 2016-11-01 at 1 08 12 pm

Cool simple enough?

**Comment by thejameskyle** [comment]
Yeah that should be fine

**Pull request merged**
