### PR TITLE
Upgrade lodash from 2.4.1 to 4.13.1 & change from // to https

### PR DESCRIPTION
**Pull request by peterpme**
Paul Irish says that `//` is now an anti pattern.

Primarily, I came here to update lodash in the REPL

Thanks!

### CODE REVIEW

**Comment by hzoo** [comment]
Thanks, we don't have tests for the repl so I think we would need to check all calls in the relevant js files to make sure everything still works?

**Comment by peterpme** [comment]
Hey,

Thanks for the quick reply!

There are 19 counts of `_.` within this repo.

- 8 of them come from `babel.js` and include methods like `isFunctionDeclaration` which I'm not familiar with.
- 6 of them come from `docs.js`
  - `memoize`
  - `each`
- 5 of them come from `repl.js`
  - `assign`
  - `debounce`

The remaining are still supported by lodash today.

Thanks!

**Comment by peterpme** [comment]
@hzoo any chance we can still make this happen? Thanks!

**Comment by hzoo** [comment]
Yeah sorry 😛 , just have to lookup changes

**Comment by peterpme** [comment]
Its worth noting the compiled babel.js file included has lodash 3 as a dependency

**Comment by peterpme** [comment]
:cry: @hzoo if there's anything I can do to help you please let me know!

**Comment by hzoo** [comment]
ok should be ok if you want to fix merge conflicts (as long as the repl works)

**Comment by peterpme** [comment]
@hzoo ready when you are! Thanks again

**Pull request merged**
