### PR TITLE
New User: AutoLotto

### LINKED ISSUE #470: New User: AutoLotto
- Name: AutoLotto
- Homepage url: https://autolotto.com
- Logo: see below

green logo png
green on white
white logo png
white on green

### PR DESCRIPTION
**Pull request by gsvolt**
fixes #470 
Added 500x200 logo for AutoLotto and added their site in users.yml

### CODE REVIEW

**Comment by thejameskyle** [comment]
Can you resolve the conflicts in this branch?

**Comment by gsvolt** [comment]
hey @thejameskyle I merged Issue472 into Issue472. Let me know if that resolves the merge conflict (I think it should as it now has GoDaddy and AutoLotto's logos.

I'll wait for you to merge PRs I submit for new users before I pick up the next issues (apparently there a many outstanding) so this doesn't happen again. I got to impatient I guess lol

Cheers!

**Comment by thejameskyle** [comment]
I'm going to cherrypick your commits because I was hoping for a rebase not a merge as that adds extra commits.

**Comment by thejameskyle** [comment]
Merged via https://github.com/babel/babel.github.io/commit/f96133ad2ebf1dcddf61d010ceac27f858a28736

**Comment by thejameskyle** [comment]
@gsvolt If you do open PRs for the rest can you do them in reverse order so that they are added to the page in the order they were opened?

**Pull request closed without merging**
