### PR TITLE
move async functions to stage 3 (docs)

### PR DESCRIPTION
**Pull request by michaelficarra**
See https://github.com/babel/babel/pull/2464.

### CODE REVIEW

**Comment by thejameskyle** [comment]
This just needs to wait for a publish. @sebmck ?

**Comment by sebmck** [comment]
I'll do it tomorrow.

**Comment by thejameskyle** [comment]
sooo

**Comment by loganfsmyth** [comment]
This can land now that 5.8.29 is out, right?

**Pull request merged**
