### PR TITLE
Add Babel user: directlyrics

### PR DESCRIPTION
**Pull request by ymschaap**
Would love to be listed in your users list.

### CODE REVIEW

**Comment by existentialism** [comment]
@ymschaap thanks for the PR! any chance you have a svg version of the logo (sized to 500x200 & optimized)?

**Comment by ymschaap** [comment]
Not right now. I would have to lookup the source, and create a true SVG.

**Comment by ymschaap** [comment]
@existentialism replaced it with the SVG

**Comment by existentialism** [comment]
@ymschaap thanks!

**Pull request merged**
