### PR TITLE
Use cdn.rawgit.com instead of rawgit.com

### PR DESCRIPTION
**Pull request by rgrove**
See https://rawgit.com/faq#rawgit-com-in-production

### CODE REVIEW

**Comment by sebmck** [comment]
@thejameskyle Why the fuck are we using rawgit in the first place

**Comment by rgrove** [comment]
Because it's awesome, guys. Duh.

**Comment by thejameskyle** [comment]
@sebmck Because we're waiting on this to get merged https://github.com/kenwheeler/slick/pull/1164

**Comment by thejameskyle** [comment]
:+1:

**Pull request merged**
