### PR TITLE
add Money Forward

### PR DESCRIPTION
**Pull request by khirayama**
#415

### CODE REVIEW

**Comment by thejameskyle** [comment]
You didn't add the image. See https://github.com/babel/babel.github.io/pull/409 for an example

**Comment by khirayama** [comment]
Thank you for your comment.  
I added a corp image. Please check again.

**Comment by thejameskyle** [comment]
The image needs to be 500px x 200px. Please also run it through [ImageOptim](https://imageoptim.com/)

**Comment by khirayama** [comment]
I'm sorry. I resized an image.

**Pull request merged**
