### PR TITLE
New User : [Housing]

### PR DESCRIPTION
**Pull request by ritz078**
We are using babel in our company and its great. Added [housing.com](https://housing.com)

### CODE REVIEW

**Comment by thejameskyle** [comment]
Can you resize the image to be 500x200 and run it through ImageOptim?

**Comment by ritz078** [comment]
@thejameskyle done.

**Comment by thejameskyle** [comment]
Thanks

**Comment by thejameskyle** [comment]
http://babeljs.io/users/#Housing

**Pull request merged**
