### PR TITLE
Cleanup main page bash code snippets

### PR DESCRIPTION
**Pull request by seedofjoy**
For #1002 

On main page:
- Changed highlight language from JS to shell in cli commands
- Remove `$` symbols
- Add `$` with :before content

### CODE REVIEW

**Comment by xtuc** [comment]
This is great :+1: 

I added support for code blocks generated from markdown.

**Comment by xtuc** [comment]
As said @hzoo, some codes must be splited. This is causing weird situations : 

basic-setups

**Comment by seedofjoy** [comment]
I just started to work with code and realized that adding `$` with `before` maybe not a good idea. Some blocks no need to split, but `$` displayed only on first line.
For example:

What do you think?

**Comment by xtuc** [comment]
@hzoo @hzoo I guess we should split blocks of code first ?

**Comment by hzoo** [comment]
Yeah I did some of that for the presets at least - will have to look at the other places

**Comment by seedofjoy** [comment]
Sorry, will open new PR

**Pull request closed without merging**
