### PR TITLE
New User: BitMEX

### LINKED ISSUE #719: New User: BitMEX
- Name: BitMEX
- Homepage url: https://www.bitmex.com
- Brand Guidelines/Licensing: :shipit: Logo is fair game
- Logo: https://www.bitmex.com/img/bitmex-logo-alt.png

:100: :+1:

### PR DESCRIPTION
**Pull request by STRML**
Closes #719

### CODE REVIEW

**Comment by thejameskyle** [comment]
Needs rebase, needs to be 500x200 (2.5x1), and please run through `svgo`

**Comment by STRML** [comment]
My bad, thanks - ran it through svgo though, it's just large (text at the bottom).

**Comment by STRML** [comment]
Given that size on an svg is just an attribute, and the browser scales it, does it really matter? I'm actually curious, if, say, there's a performance difference or anything tangible.

screen shot 2016-02-14 at 1 24 07 pm

**Comment by thejameskyle** [comment]
There tends to be differences between different browsers

**Comment by STRML** [comment]
:+1: Thanks for your patience

**Comment by thejameskyle** [comment]
Sorry, I don't mean to be nitpicky but would it be okay to remove the white background?

**Comment by STRML** [comment]
No worries, amended.

**Pull request merged**
