### PR TITLE
Move script files to end of body. Closes #19

### LINKED ISSUE #19: Move script files to end of <body>

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This PR literally moves all scripts to the bottom of the page - because #perfmatters.
The idea of these changes is to let author(s) of the page to easily add new client side code by modifying either page template (layout) file front metter declaration(s) or by modifying page front metter declaration(s).

For example - the web site is using Bootstrap framework cross-site. So the idea of solution in this PR is to declare that Bootstrap is to be used everywhere on the layout level:
```liquid
---
layout_external_scripts:
 - //cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js
 - //cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js
 - //cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js
---
```

and then simply use that information to write script tag into page body:
```liquid
{% if page.layout_external_scripts %}
  {% for script_path in page.layout_external_scripts %}
  <script src="{{ script_path }}"></script>
  {% endfor %}
{% endif %}
```

The local scripts are using cache busting solution.

As there could be 4 types of scripts (as the time of writing) within web site, there are 4 different lists declared:
- external on the layout level
- external on the page level
- local on the layout level
- local on the page level

The scripts are rendered later in the above list order (if they are declared and available in the `page` variable ofc).

This PR commits:
- remove render-blocking scripts from page haed section
- move embedded scripts from markup to JavaScript file
- prepare site-wide solution based on front metter declared variables
- specify layout related external and web site scripts in templates
- specify page specific external and web site scripts in templates
All scripts used on the website are now declared using list in front
metter sections. This allows to build up the correct order of script inclusion
in the given page and allows the future optimization if script minifying
is to be introduced.

I've tried to test everything, comparing fetched scripts with current live version (and checking for scripts errors), but I'd ask someone to verify this PR as well.

@thejameskyle
This should improve overall page rendering speed and responsiveness.

Thanks!

### CODE REVIEW

**Comment by thejameskyle** [comment]
Can you combine the social scripts into one file?

**Comment by peterblazejewicz** [comment]
@thejameskyle sure!

**Comment by thejameskyle** [comment]
You might be able to combine page and layout scripts by using the `push` helper.

```js
{{ page.scripts | push '/scripts/docs.js' }}
{{ page.external_scripts | push '//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js' }}
```

**Comment by peterblazejewicz** [comment]
> Can you combine the social scripts into one file?

Update, combined - not squashed to see as separate commit as of now

**Comment by peterblazejewicz** [comment]
@thejameskyle 
> You might be able to combine page and layout scripts by using the push helper.

Not exactly sure here what I'm supposed to do. I see that this could remove some code from  `scripts.html` - but I can't get how to use this in front metter declarations.

**Comment by thejameskyle** [comment]
Well you wouldn't put it in the front matter.

```liquid
---
layout: default
---
{{ page.scripts | push '/foo.js' }}
```

> I see that this could remove some code from scripts.html

I don't care so much about the front matter as much as the ability to extend it


```liquid
<!-- _layouts/default -->
---
layout_external_scripts:
  - foo.js
--- 

<!-- _layouts/page -->
---
layout: default
layout_external_scripts:
  - bar.js
---
```

This would output only `bar.js` for anything using the page layout.


```liquid
<!-- _layouts/default -->
{{ page.external_scripts | push 'foo.js'}} 

<!-- _layouts/page -->
---
layout: default
---
{{ page.external_scripts | push 'bar.js'}}
```

Where this would output both.

**Comment by peterblazejewicz** [comment]
@thejameskyle 
James, sorry. This does not work for me:
https://github.com/peterblazejewicz/babel.github.io/commit/1003bcb7df0aa745d6aa9cee3c08959c61ec36da
Maybe I'm missing here something simple, as that is a first time I've refactored/written such code in Jekyll/Liquid

It seems that `push` filter does not work here for this specific use case - so nothing is printed from `scripts.html` partial into output page

**Comment by thejameskyle** [comment]
Alright, just revert that last commit then and squash your commits please.

**Comment by peterblazejewicz** [comment]
@thejameskyle 
Done. I'm really to revisit the topic of optimizing dev code for better solution as soon as I found similar solution somewhere. Maybe some static generated CMS, I'll check Shopify sources as well for their wast Liquid resources.
Thanks!

**Comment by peterblazejewicz** [comment]
I want to close it in favour of fresh look into the topic:
https://github.com/babel/babel.github.io/issues/19#issuecomment-129870683
Thanks!

**Pull request closed without merging**
