### PR TITLE
Add a link to submitted users PRs

### PR DESCRIPTION
**Pull request by hzoo**
Or we just remove the issue part since we ask them to make a PR anyway

@thejameskyle

### CODE REVIEW

**Comment by thejameskyle** [comment]
Yeah do you want to update this to just be "open a pr"

**Comment by hzoo** [comment]
Updated - should I keep the or?

**Comment by thejameskyle** [comment]
Oh no I meant to get rid of the "open an issue" part

**Comment by hzoo** [comment]
Ahh sorry that makes sense too - Il update

**Comment by hzoo** [comment]
Ok - https://github.com/babel/babel.github.io/commit/ea69f3d9181ad68768f0764f7f23d8353a6814ec

**Pull request merged**
