### PR TITLE
REPL: Add env to available presets.

### PR DESCRIPTION
**Pull request by yavorsky**
This PR adds [env](https://github.com/babel/babel-preset-env) to the list.

It also adds new dropdown menu that emulates preset-env configuration: Ability to define browsers in [borwserslist](https://github.com/ai/browserslist)'s format and electron + node.js as additional options. 
After you change one of the options REPL recompiling all stuff into the **code that works on specified targets with the minimum possible transformation**.

I've created [babel-preset-env-standalone](https://github.com/yavorsky/babel-preset-env-standalone) - wrapper for original preset that doesn't change behavior but just making a bundle. So we can just add it with `Babel.registerPreset`.

Tested on last chrome, safari, FF, ie11, edge.

### CODE REVIEW

**Comment by existentialism** [comment]
Awesome @yavorsky!

Should we hide the targets option by default, to avoid it from appearing then disappearing on initial load:

mm

**Comment by existentialism** [comment]
Should we catch this error:

image

**Comment by yavorsky** [comment]
@existentialism 
Yes, I'll update targets option to be hidden by default. Thanks 👍

I don't think we need to hide browserslist error. It's very useful to understand that query has the wrong format. I can write something like `current chrome and safari` and without errors think that it's correct behavior.

**Comment by hzoo** [comment]
Awesome - and maybe we could turn on the debug option on for logging? can be another pr

**Comment by yavorsky** [comment]
Thanks, guys!
@hzoo Cool! Thinking where is better to output it. Just in the console or make additional section the prettiest way... 🤔

**Comment by hzoo** [comment]
I was thinking just the console for now is good but would be nice to have a UI as well

**Comment by Daniel15** [comment]
@yavorsky 

> I've created [babel-preset-env-standalone](https://github.com/yavorsky/babel-preset-env-standalone) - wrapper for original preset that doesn't change behavior but just making a bundle.

I'm happy to merge this directly into babel-standalone if you send a pull request 😃

**Comment by yavorsky** [comment]
@Daniel15 Sure! But it weights about 3mb, currently working on reducing the size.

**Comment by Daniel15** [comment]
We could bundle it with babel-standalone but make it a separate file, like how babili-standalone is separate. People that want to use it would load both `babel.js` and `env.js` (or whatever we call it), similar to how things are currently.

**Pull request merged**
