### PR TITLE
Update polyfill doc according to npm package name

### PR DESCRIPTION
**Pull request by ghoullier**
Update polyfill page according according to npm package name babel-core

### CODE REVIEW

**Comment by thejameskyle** [comment]
I've never been quite sure how to break down the docs by `babel` and `babel-core`. @sebmck what do you think?

**Comment by sebmck** [comment]
@thejameskyle Yeah, the distinction is really shit. I'm not sure how to distinguish between the two in a clear way in the docs. In the next major it might be worth retiring the `babel` package in favor of `babel-cli` and `babel-core`.

**Comment by thejameskyle** [comment]
Maybe, I also feel like we should tell people to install babel as

```sh
$ npm install --save-dev babel babel-core
```

This dedupes the dependency when installed at once (`babel` depends on it's peer dep), which means that `babel` and one of the other tools like `gulp-babel` will depend on the same copy.

Then the docs can always refer to `babel-core` for JS usage and `babel` (or `babel-cli`) for CLI usage.

**Comment by sebmck** [comment]
Should we really be encouraging that behaviour when npm 3 has tree flattening?

**Comment by thejameskyle** [comment]
Well if people are `require('babel-core')`-ing then it should be an installed dep.

**Comment by hzoo** [comment]
Changed to `babel-polyfill` so closing - thanks anyway!

**Pull request closed without merging**
