### PR TITLE
Help move package docs to babel/babel

### PR DESCRIPTION
**Pull request by raspo**
Companion to https://github.com/babel/babel/pull/4931

- transform-class-properties
- transform-decorators
- transform-do-expressions
- transform-es3-member-expression-literals
- transform-es3-property-literals
- transform-es5-property-mutators
- transform-eval
- transform-exponentiation-operator
- transform-export-extensions
- transform-flow-comments
- transform-flow-strip-types
- transform-function-bind
- transform-jscript
- transform-object-assign
- transform-object-rest-spread
- transform-object-set-prototype-of-to-assign
- transform-proto-to-assign
- transform-runtime
- transform-strict-mode
- undeclared-variables-check

### CODE REVIEW

**Comment by xtuc** [comment]
Great PR, thanks.

I moved all package descriptions in the Jekyll page header.

transform-es3-property-literals

LGTM :+1:

**Comment by existentialism** [comment]
Duplicate text on flow-comments:
image

**Comment by raspo** [comment]
I removed the duplicate content and moved a few more descriptions in the header.

**Comment by xtuc** [comment]
LGTM :+1: 

/cc @hzoo

**Pull request merged**
