### PR TITLE
Fix anchor tag links: es6 -> es2015 - fixes #306

### LINKED ISSUE #306: Wrong links in experimental page
Hi.

The links in this page are broken http://babeljs.io/docs/usage/experimental/
They point to http://babeljs.io/docs/learn-es6#xxxx instead of http://babeljs.io/docs/learn-es2015#xxxx

### PR DESCRIPTION
**Pull request by hzoo**

### CODE REVIEW

**Comment by thejameskyle** [comment]
Thanks

**Comment by thejameskyle** [comment]
Actually in order to avoid a redirect which loses the hash. It needs the trailing slash (i.e. `/learn-es2015/#symbols`)

**Comment by hzoo** [comment]
Oh - should I add the `/` to all of the `learn-es2015#`?

**Comment by thejameskyle** [comment]
Yeah, would you mind making a PR?

**Pull request merged**
