### PR TITLE
Object.assign example Point -> shape

### PR DESCRIPTION
**Pull request by tiemevanveen**
Shouldn't `Point ` be a `shape` or a `rect` or something? And with a lowercase letter? 
Or am I missing the point (pun not intended, haha) here?

### CODE REVIEW

**Comment by loganfsmyth** [comment]
The `origin` property in this example is meant to be a static property on the `Point` constructor, so this should make sense.

**Comment by tiemevanveen** [comment]
Okay. So just to be clear. This `Object.assign` adds a static property `origin` to `Point` and that also happens to be a `Point`?

**Comment by loganfsmyth** [comment]
Yes, so it's essentially doing `Point.origin = new Point(0, 0);` so that when doing math you can use the static `Point.origin` point as the origin.

**Comment by tiemevanveen** [comment]
Check. Thanks for explaining.

**Pull request closed without merging**
