### PR TITLE
New User: Snapdeal

### PR DESCRIPTION
**Pull request by getonlineamit**
New User: Snapdeal

### CODE REVIEW

**Comment by hzoo** [comment]
@getonlineamit looks like your commit is not there?

**Comment by getonlineamit** [comment]
Getting this error while pushing ...@hzoo
ERROR: Permission to babel/babel.github.io.git denied to getonlineamit.

**Comment by xtuc** [comment]
@getonlineamit Fork this repository first and then you need to work on it.

**Comment by getonlineamit** [comment]
@xtuc i have already forked this repository.

**Comment by hzoo** [comment]
looks like you are trying to push from the wrong branch?

`getonlineamit  wants to merge 1 commit into master from kaicataldo-patch-1`

**Pull request closed without merging**
