### PR TITLE
Update repo for sprockets-es6

### PR DESCRIPTION
**Pull request by sudodoki**
Previous repo mentioned in docs is now 404. Might be something @josh might provide more info about. //cc @TannerRogalsky

### CODE REVIEW

**Comment by thejameskyle** [comment]
@josh was the repo transferred?

**Comment by TannerRogalsky** [comment]
:+1: That is the new main repo for that gem as per this pull request: https://github.com/TannerRogalsky/sprockets-es6/pull/1

The rubygems page also points to my repo now. https://rubygems.org/gems/sprockets-es6

**Comment by josh** [comment]
The sprockets-es6 gem is deprecated. The feature is being rolled into sprockets core so people won't have to install anything.

**Comment by sudodoki** [comment]
@josh but it still not there and we need something to be there meanwhile :smile_cat:

**Comment by sebmck** [comment]
Thanks everyone for their clarification :) Happy to update as things are released.

**Pull request merged**
