### PR TITLE
New User: Behance

### PR DESCRIPTION
**Pull request by hzoo**
Hi! Ran through svgo too.

### CODE REVIEW

**Comment by thejameskyle** [comment]
Needs to be 500x200 (2.5x1)

**Comment by hzoo** [comment]
Is it alright just changing `viewBox="0 0 500 200"`?

**Comment by thejameskyle** [comment]
No, that does this: https://github.com/hzoo/babel.github.io/blob/add-behance/images/users/behance.svg

**Comment by thejameskyle** [comment]
Also, do you have a version of the logo without the blue background?

**Comment by hzoo** [comment]
Ok I tried my best

**Comment by thejameskyle** [comment]
Looks fine

**Comment by thejameskyle** [comment]
http://babeljs.io/users/#Behance

**Comment by hzoo** [comment]
Thanks!

**Pull request merged**
