### PR TITLE
Guest post: React on ES6+

### PR DESCRIPTION
**Pull request by steveluscher**

### CODE REVIEW

**Comment by thejameskyle** [comment]
Cool, I'll take this over and get in published early this week.

**Comment by thejameskyle** [comment]
Sorry this hasn't gone out, I've been at conferences both in SF and in London and I'm spending the week in London now.

**Comment by steveluscher** [comment]
No problem

**Comment by sebmck** [comment]
Ping @thejameskyle

**Comment by thejameskyle** [comment]
Sorry I know, I suck. I'll start on this now

**Comment by sebmck** [comment]
Thank you so much for doing this @steveluscher!

**Pull request merged**
