### PR TITLE
Changed loaders to rules in webpack setup

### PR DESCRIPTION
**Pull request by Diogomartf**
Changed loaders to webpack new syntax rules.

This fixes issue [#1188](https://github.com/babel/babel.github.io/issues/1184).

### CODE REVIEW

**Comment by existentialism** [comment]
@Diogomartf thanks for the PR!

Wonder if it's worth having webpack 1 and 2 options in the setup helper?

/cc: @hzoo @xtuc

**Comment by xtuc** [comment]
I think it's confusing for users. I would just mention to add the loader.

**Comment by hzoo** [comment]
I'm ok with that - just do a section for webpack 1 and webpack2

**Comment by hzoo** [comment]
Or default to webpack 2 and a section for webpack 1 since webpack 2 is installed via `npm install webpack`

**Comment by Diogomartf** [comment]
So what you are saying is to point the webpack button to webpack 2 and add a new button webpack 1 pointing to webpack ?

**Comment by hzoo** [comment]
Nah I was thinking there would be only 1 button but we provide instructions for webpack 1 below if we really wanted to.

**Comment by Diogomartf** [comment]
Ok got it.

**Comment by xtuc** [comment]
Yes, that's ok for me :+1:

**Comment by Diogomartf** [comment]
What should I do, update the PR with that?

**Comment by existentialism** [comment]
@Diogomartf yep!

**Comment by Diogomartf** [comment]
On it.

**Comment by hzoo** [comment]
Cool thanks!

**Pull request merged**
