### PR TITLE
Make REPL editors resizable by width.

### PR DESCRIPTION
**Pull request by seedofjoy**
Solves #825 

Makes resizable editor columns (10px transparent zone).
Size set in percent, panel minimum size - 20%.
repl-resize

### CODE REVIEW

**Comment by brigand** [comment]
Does this have any issues if you move the mouse too fast? I remember having issues with that on a past project.

**Comment by seedofjoy** [comment]
Only that cursor may change from `col-resize` to `text`. I can fix this by adding class to parent component with `cursor: col-resize` during resize phase. But actually this almost imperceptible.

**Comment by brigand** [comment]
Cool, this is much nicer than the implementation I went with (an invisible fixed position div). TIL

**Comment by hzoo** [comment]
Awesome! - might be ok to make 90-10 if it still works. Thoughts on adding a different color or signal on hover? astexplorer.net has this

**Comment by seedofjoy** [comment]
Forgot about `babel-repl-errors` and `babel-repl-console` panels. I think they should resize with inputs (`errors` = `input` and `console`=`output` width).
In next commit will add colors, hover, 90-10, (and resizing `errors` and `console`?)

**Comment by hzoo** [comment]
yeah looks like there was an earlier similar issue about that as well https://github.com/babel/babel.github.io/issues/90

**Comment by seedofjoy** [comment]
What do you think about this? It's work nice (`errors` and `console` panels resize well), but unfortunately add visual styles with resize bar to bottom panel without major changes in layout very hard.

**Comment by hzoo** [comment]
Lgtm - there are some layout issues with those anyway - if necessary we should change then?

**Comment by seedofjoy** [comment]
out
Made some minor layout changes to fit resize bar over the entire height

**Comment by xtuc** [comment]
Awsome :+1:. LGTM also.

**Comment by seedofjoy** [comment]
I have tested on Chrome and Safari. In IE I can check tomorrow

**Comment by hzoo** [comment]
We can merge now too

Looks like the logs don't show up for me on the bottom right anymore?

test:

- [x] resize
- [x] syntax errors on the left console
- [ ] output on the right console

**Comment by hzoo** [comment]
actually I tried it again and it works fine? dono what happened before

**Comment by hzoo** [comment]
Awesome stuff! Thanks @seedofjoy (will add you to the repo if you'd like)

**Comment by seedofjoy** [comment]
@hzoo Great, thank you! :octocat:

**Comment by hzoo** [comment]
and feel free to join our slack.babeljs.io if you haven't already

**Pull request merged**
