### PR TITLE
Updated share image to be babel & not 6to5

### PR DESCRIPTION
**Pull request by jhorwit2**
Updated the share image!

### CODE REVIEW

**Comment by thejameskyle** [comment]
Would you mind getting it a little more centered around the text?

**Comment by jhorwit2** [comment]
yup.

**Comment by jhorwit2** [comment]
@thejameskyle That work?

**Comment by thejameskyle** [comment]
For sure, just squash please and I'll merge

**Comment by jhorwit2** [comment]
@thejameskyle :+1:

**Comment by thejameskyle** [comment]
Sweet, thanks!

**Pull request merged**
