### PR TITLE
add Docsearch

### PR DESCRIPTION
**Pull request by maxiloc**
@hzoo, Following #438,  and the discussion you had by email with Remy from Algolia, here is the docsearch implementation

yyksljifwg

### CODE REVIEW

**Comment by hzoo** [comment]
Awesome!

Also was wondering if anything needs to be done to get keyboard shortcuts working (up and down arrows)

**Comment by hzoo** [comment]
Hm we have a lot of the same settings so if I type API I get 
screen shot 2016-11-15 at 10 30 53 am

rather than anything under usage

screen shot 2016-11-15 at 10 30 16 am

**Comment by maxiloc** [comment]
@hzoo The up and down arrow are handled by default, but the yellow highlight was a bit to transparent. It should be better now.
There was a mistake in the docsearch config and the usage pages were not picked up correctly. It should be ok now.

Tell me if it's good for you.

**Comment by hzoo** [comment]
yeah it should be everyhting in https://github.com/babel/babel.github.io/tree/master/docs

looks better now
screen shot 2016-11-15 at 11 00 34 am

**Comment by hzoo** [comment]
@maxiloc how does the config work or is that on your end? Was wondering how to get better results if we find there are issues. I'm cool to merge this now though

**Comment by hzoo** [comment]
Since it looks like the top level h1 isn't picked up. Like if I search polyfill I might expect that specific page to show up http://babeljs.io/docs/usage/polyfill

**Comment by maxiloc** [comment]
You can have a look at the config here: https://github.com/algolia/docsearch-configs/blob/master/configs/babeljs.json. It's a set of simple rules that are used to crawl the website. You can make PRs if you need or just ping us when you see something that is not optimal and we'll fix it.

We then crawl the site automatically with https://github.com/algolia/docsearch-scraper

**Comment by hzoo** [comment]
Oh ok thanks a lot!

I was wondering given you added 
```
  "start_urls": [
    "http://babeljs.io/docs/",
    "http://babeljs.io/docs/usage/api"
  ],
```

whether we need to add the rest https://github.com/babel/babel.github.io/tree/master/docs/usage

**Comment by maxiloc** [comment]
I tweaked a bit the config the polyfill should appear first now

**Comment by maxiloc** [comment]
No we don't need to add it all urls manually. We have http://babeljs.io/docs/usage/api because http://babeljs.io/docs/ is a 404 but we need it to accept all http://babeljs.io/docs/* urls

**Pull request merged**
