### PR TITLE
Add Under Armour

### PR DESCRIPTION
**Pull request by paultyng**

### CODE REVIEW

**Comment by thejameskyle** [comment]
Can you resize this to be 500x200 (2.5x1)?

**Comment by paultyng** [comment]
Sure give me a few

**Comment by paultyng** [comment]
@thejameskyle How's that? Sorry I should have caught it first time through.

**Comment by thejameskyle** [comment]
http://babeljs.io/users/#Under%20Armour

**Comment by thejameskyle** [comment]
Thanks

**Pull request merged**
