### PR TITLE
Fix documentation to not install babel-cli globally

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
- Followup of https://github.com/babel/babel/pull/3150
- Fixes https://github.com/babel/babel.github.io/issues/632

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
I did not update the instruction to install `babel-cli` globally from the babel doctor blog post as I am not sure it will work without installing globally.
monosnap 2015-12-13 17-52-01

//cc @jmm

**Comment by thejameskyle** [comment]
This is an excerpt from the babel-user-handbook I'm writing right now: https://gist.github.com/thejameskyle/0a12e411a556bbf76130

I want to present it more along these lines in the documentation, I'm not sure how yet

**Comment by jmm** [comment]
@prathamesh-sonpatki Thanks for the contributions! I see what @thejameskyle is saying -- it's kind of muddled if we just delete the `-g`. Hopefully despite the instructions most people know to install it as a local dep and how to then utilize it and we can get some better docs up soon for those who don't.

Even if this doesn't get merged, I appreciate the effort.

**Comment by prathamesh-sonpatki** [comment]
@thejameskyle Thanks for the feedback. I modified the gist a bit - https://gist.github.com/prathamesh-sonpatki/3f038476594a38a9e5f1 so that it fits current documentation structure of `Installation` and `Usage`.  Does this sound good?

**Comment by thejameskyle** [comment]
Works for me, want to update this PR?

**Comment by prathamesh-sonpatki** [comment]
@thejameskyle Please review

**Comment by thejameskyle** [comment]
Thanks

**Pull request merged**
