### PR TITLE
add preset-stage-x docs

### PR DESCRIPTION
**Pull request by hzoo**
Ref https://github.com/babel/babel/pull/2649

should publish the npm packages when merging this

### CODE REVIEW

**Comment by thejameskyle** [comment]
Awesome, thank you

**Comment by sebmck** [comment]
This should not have been merged until I have published the packages.

**Comment by hzoo** [comment]
Probably didn't see the message I put in the description - next time I'll do a warning/wip in the title

**Comment by thejameskyle** [comment]
Right, my bad

**Pull request merged**
