### PR TITLE
Fix Broken links

### PR DESCRIPTION
**Pull request by maxdow**
Shortcuts in the main page doesn't work. This is not perfect because links are hardcoded (it will break if the domain change ) but it should work

### CODE REVIEW

**Comment by xtuc** [comment]
Links aren't broken, they are pointing to anchors in the page.

Did you encourter this issue on the blog post on the Babel's website (https://babeljs.io/blog/2016/12/07/the-state-of-babel) ?

**Comment by maxdow** [comment]
Exact but it doesn't work when anchors are not in the page, like in the main blog page ( https://babeljs.io/blog/ ) . This is the issue , on babel's website yes

**Comment by xtuc** [comment]
Ok yes, good point.

I guess we could also update the description of the post to avoid theses links on the page.

/cc @hzoo

**Comment by maxdow** [comment]
Absolutely, I think it's a better fix ;)

**Comment by hzoo** [comment]
Yeah its just auto adding the first thing there so I dono 😄 we could remove.

**Comment by xtuc** [comment]
Thanks @maxdow :+1:

**Comment by maxdow** [comment]
You're welcome, thanks for all the hard work and thanks @hzoo for this really good recap on the state of babel

**Pull request merged**
