### PR TITLE
added instruction to install ruby as prerequisites

### LINKED ISSUE #782: Add instructions on local setup
Add some instructions on local setup if stuff isn't installed

https://github.com/babel/babel.github.io/issues/258#issuecomment-111142413
> $ # install ruby
$ gem install bundler # if ruby hasn't been installed
$ bundle install # if you haven't already
$ gem install jekyll-redirect-from
$ jekyll s

### PR DESCRIPTION
**Pull request by sarbbottam**
fixed #782 

@hzoo could you take a look?

### CODE REVIEW

**Comment by hzoo** [comment]
Looks good?

So if bundler isn't installed it we print a message. I'm assuming if you install ruby it comes with `gem`.

And we may need to use `make build`?

**Comment by sarbbottam** [comment]
>I'm assuming if you install `ruby` it comes with `gem`.

I am not sure, `ruby` and `gem` came pre-installed in mac. However, we could add an instruction about [`gem`](https://rubygems.org/pages/download).

>And we may need to use `make build`?

hmm, not sure, since `ruby` and `gem` is a system/user level install and not local to the repo.

**Comment by sarbbottam** [comment]
Also, [current `make build` seems to be redundant](https://github.com/babel/babel.github.io/pull/776).

**Comment by hzoo** [comment]
Right, I was referencing make build in the makefile, but I see you made https://github.com/babel/babel.github.io/pull/776

**Pull request merged**
