### PR TITLE
Update learn-es6.md

### PR DESCRIPTION
**Pull request by JunJianSyu**
Examples of operational errors authors wrote in my node es6 environment, I modified the example

### CODE REVIEW

**Comment by thejameskyle** [comment]
I don't understand why you want to make this change.

**Comment by JunJianSyu** [comment]
Example is wrong, I think this is misleading. Why not change

**Comment by thejameskyle** [comment]
What is wrong about the example?

**Comment by JunJianSyu** [comment]
ReferenceError: MyClass is not defined    
IIFE function not export MyClass

**Comment by JunJianSyu** [comment]
Please read my submitted commit code

**Pull request closed without merging**
