### PR TITLE
New User: TES Global

### PR DESCRIPTION
**Pull request by aamirafridi**
- name: TES Global
 - url: https://www.tes.com/

### CODE REVIEW

**Comment by aamirafridi** [comment]
@gregersrygg can you please merge this

**Comment by gregersrygg** [comment]
@aamirafridi I'm not part of the Babel team, so I don't have access.

**Comment by aamirafridi** [comment]
@hzoo can you merge this please?

**Comment by aamirafridi** [comment]
@hzoo is there any reason this cannot be merged?

**Comment by thejameskyle** [comment]
Number of issues:

- Image needs to be 500x200 (2.5x1)
- Please run it through `svgo`
- Needs rebase

**Comment by aamirafridi** [comment]
Its a nightmare to rebase a forked branch. Closing this and creating a new one :(

**Comment by aamirafridi** [comment]
@thejameskyle Please merge this ASAP https://github.com/babel/babel.github.io/pull/587

**Pull request closed without merging**
