### PR TITLE
Add some testing for CI

### PR DESCRIPTION
**Pull request by existentialism**
Couple things I'm hoping we'll get with each PR:

- Errors if any broken links 
- Errors if any orphan pages
- Errors if referencing any missing images
- Linting issues with markdown
- Malformed HTML

### CODE REVIEW

**Comment by xtuc** [comment]
Awesome, sounds great!

**Comment by xtuc** [comment]
Should we then add the CI badge to the README?

[Build Status](https://travis-ci.org/babel/babel.github.io)

**Comment by hzoo** [comment]
I was thinking this could be a separate CI cron job thing but we could check if git submodules are out of date and then update them (or just run the update commands)

**Comment by xtuc** [comment]
It seems possible to deploy the website using a Travis job ([source](http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/)).

We have than the possible to script the website before its deployement.

We still need to keep submodules up-to-date in master.

**Comment by xtuc** [comment]
Looks good :+1: 

@hzoo Could we activate the CI for that repo to test this PR?

**Comment by existentialism** [comment]
Yay:

image

**Comment by existentialism** [comment]
Landing this with the caveat that we'll continue to tweak this as we go. I think the broken links check is a big 👍

**Pull request merged**
