### PR TITLE
Fix babili github links

### PR DESCRIPTION
**Pull request by existentialism**
Moved the `from` variable from the include up to the page and added a mapping of source to GH url

### CODE REVIEW

**Comment by xtuc** [comment]
Nice job!

@boopathi made a PR #1008 trying to fix this.

Should we point to the actual package's README when clicing on "Edit this page" (https://github.com/existentialism/babel.github.io/blob/8a19a5248424898e5776c9bff9a06f2d5d19fa91/_layouts/page.html#L26). Linking to this https://github.com/babel/babel.github.io/blob/master/docs/plugins/transform-property-literals.md for example make no more sense.

I will update the documentation on how to contribute on the website in the README.

**Comment by existentialism** [comment]
@xtuc good idea, updated!

**Comment by xtuc** [comment]
Great, LGTM :+1:

**Comment by hzoo** [comment]
Awesome stuff!

**Pull request merged**
