### PR TITLE
Remove "class-constructor-call" plugin

### PR DESCRIPTION
**Pull request by xtuc**
Will be removed in Babel 7 (babel/babel#5119)

### CODE REVIEW

**Comment by hzoo** [comment]
I know we normally delete it but since it's the docs it might be better to say unmaintained/removed - we don't want the website url to get remove (unless we create another page for removed proposals and redirect there)

**Comment by xtuc** [comment]
Yes of course. I think we should have a deprecated / do-not-use label for the website.

**Comment by hzoo** [comment]
But we should update it if you think it could be worded up now that we are removing it from the repo/unmaintained

**Comment by xtuc** [comment]
There are already depreciation notes in both plugin list and on the plugins page. In the README on babel/babel there is also a note.

I think it's pretty obvious.

We could remove it from the plugin list but keep the page.

**Pull request closed without merging**
