### PR TITLE
New User: pebble {code}

### PR DESCRIPTION
**Pull request by poshaughnessy**
https://github.com/babel/babel.github.io/issues/565

### CODE REVIEW

**Comment by thejameskyle** [comment]
Can you make this image 500x200 and run it through imageoptim?

**Comment by poshaughnessy** [comment]
Of course - apologies! Optimised version checked in now.

**Comment by thejameskyle** [comment]
Just needs a rebase and this will be good?

**Comment by poshaughnessy** [comment]
@thejameskyle Sorry, I tried to resolve the rebase, but the commit seems wrong. I tried to squash the commit but it didn't work, possibly because of the binary change? Perhaps it's easier for me to just do a fresh fork and pull request? Thanks for your patience!

**Comment by thejameskyle** [comment]
Manually merged in https://github.com/babel/babel.github.io/commit/03aad165d50db29a1b4ea9f48df6a15d9d713e2c

**Pull request closed without merging**
