### PR TITLE
Run, Forrest. Run!

### PR DESCRIPTION
**Pull request by steveluscher**
Life is like a box of chocolates.

### CODE REVIEW

**Comment by sebmck** [comment]
I'd actually say those sentence as "ran" instead of "run". Might be a cultural thing though. @thejameskyle?

**Comment by thejameskyle** [comment]
run is grammatically correct. As run is the past particle of run.

| | past tense | past particle |
|:---:|:---:|:---:|
| run | ran | run |
| speak | spoke | spoken |

"will be spoken" is correct.
"will be spoke" is incorrect.

**Comment by sebmck** [comment]
wtf u sayin my strayan english is wrong????

**Comment by thejameskyle** [comment]
yes

**Comment by sebmck** [comment]
bloody streuth, ur a bloody mongrel!

**Comment by thejameskyle** [comment]
This is what happens when you send a bunch of criminals to live on an island together.

**Comment by sebmck** [comment]
Says the guy from Boston.

**Comment by thejameskyle** [comment]
You want to say that to my face?!

**Comment by sebmck** [comment]
yes

| | Victoria, Australia (2013) | Boston, US (2013) |
|:---:|:---:|:---:|
| Murders (per 100k) | 3.1 | 39 |
| Rapes (per 100k) | 36.4 | 279 |
| Robberies (per 100k) | 49.8 | 1,868 |
| Assaults (per 100k) | 811.6 | 2,851 |
| Burglaries (per 100k) | 822.1 | 3,096 |
| Thefts (per 100k) | 2,010.6 | 13,147 |
| Auto Thefts (per 100k) | 258.1 | 1,610 |

i had to get the crime statistics of my **entire home state** because the crime rate in my hometown is way too late

**Comment by sebmck** [comment]
rekt

**Comment by thejameskyle** [comment]
All those numbers are higher, we're clearly better.

**Comment by sebmck** [comment]
i get more tinder matches per week than my entire home state does in deaths per year

**Comment by thejameskyle** [comment]
I get more grindr messages than thefts in Boston.

**Comment by thejameskyle** [comment]
tumblr_mudtn4e5px1syeot2o1_500

**Comment by sebmck** [comment]
lol

**Comment by thejameskyle** [comment]
You definitely just googled something related to dick pics and saw a ton of them.

Must've been glorious.

**Comment by steveluscher** [comment]
I'm including this PR in my year-end performance review, for sure.

**Pull request merged**
