### PR TITLE
Adding Squarespace to User List

### PR DESCRIPTION
**Pull request by jacobangel**
Adding svg logo and change to user data.

### CODE REVIEW

**Comment by thejameskyle** [comment]
Mind running [`svgo`](https://github.com/svg/svgo)

**Comment by thejameskyle** [comment]
Also, needs to be 500x200 (2.5x1).

**Comment by jacobangel** [comment]
Updated; thanks again for the help.

**Comment by thejameskyle** [comment]
Thanks http://babeljs.io/users/#Squarespace

**Pull request merged**
