### PR TITLE
Take me to Flavortown!

### PR DESCRIPTION
**Pull request by STRML**

### CODE REVIEW

**Comment by existentialism** [comment]
👍  LOL exactly what I wanted to do before I had to run out for the day!

Thoughts on having a more limited set of Fieri/Wikipedia-plea/Babel-esque quotes (vs just pure fieri)?

**Comment by STRML** [comment]
Sure I can trim them down to some of the funnier ones. Got some good alt quotes?

**Comment by existentialism** [comment]
Here's a few random ones riffing on Wikipedia's, but you def have as much creative freedom here as you want! :)

- A personal appeal from major of Flavortown Guy.

- If everyone reading this donated $5 our fundraiser would be over today. Donate to keep all your modules transpiled for free.

- Imagine you had a nickel for every time Babel transpiled your code. We need those nickels.

- We're almost to Flavortown. Thank you."

- "Some people are just born to cook and talk. And transpile code."

**Comment by STRML** [comment]
Updated

**Comment by sorianog** [comment]
This is wonderful :fire: :fire: :fire:

**Pull request merged**
