### PR TITLE
New User: Paperless Post

### LINKED ISSUE #457: New User: Paperless Post
- Name: Paperless Post
- Homepage url: https://paperlesspost.com
- Brand Guidelines/Licensing: N/A
- Logo: babel_logo

### PR DESCRIPTION
**Pull request by natalzia-paperless**
Closes #457

### CODE REVIEW

**Comment by thejameskyle** [comment]
Mind running this through [ImageOptim](https://imageoptim.com)

**Comment by natalzia-paperless** [comment]
@thejameskyle done!

**Comment by thejameskyle** [comment]
thanks

**Comment by thejameskyle** [comment]
http://babeljs.io/users/#Paperless%20Post

**Comment by natalzia-paperless** [comment]
great! thanks so much

**Pull request merged**
